project:
  type: website
  output-dir: docs
  pre-render: python3 assets/scripts/fetch_youtube.py
  resources:
    - assets/scripts/youtube-data.json

website:
  title: "Physics Voyage"
  site-url: "https://adityakumarphy.github.io/PhysicsVoyage.github.io/"
  favicon: assets/favicon.pnf
  search: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog          
      - href: courses.qmd
        text: Course 
      - href: project.qmd
        text: Projects
      - href: about.qmd
        text: About
  reader-mode: true
  sidebar:
    - contents: posts.qmd # Creates a blog listing sidebar
      title: Recent Posts
  page-footer:
    center: "© 2026 Physics Voyage"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: sketchy
      dark: [sketchy, assets/styles/sketchy-dark.scss]
    highlight-style:
      light: github
      dark: dracula
    css: assets/styles/styles.css
    toc: true
    include-after-body:
      - assets/includes/newsletter-popup.html
      - assets/includes/back-to-top.html
