project:
  type: website
  output-dir: docs

website:
  title: "Physics Voyage"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog          
      - href: courses.qmd
        text: Course 
      - href: project.qmd
        text: Projects
      - href: about.qmd
        text: About
  reader-mode: true
  sidebar:
    - contents: posts.qmd # Creates a blog listing sidebar
      title: Recent Posts
  #  - exclude:
   #   - projects.qmd # Hides the projects page from navigation


format:
  html:
    respect-user-color-scheme: true
    theme:
      light: sketchy
      dark: [sketchy, sketchy-dark.scss]
    highlight-style:
      light: github
      dark: dracula
    css: styles.css
    toc: true


