project:
  type: website
  output-dir: docs
  pre-render:
    - python3 assets/scripts/fetch_youtube.py
    - python3 assets/scripts/cloudinary_sync.py
    - python3 assets/scripts/cloudinary_uploader.py
  resources:
    - assets/scripts/youtube-data.json
    - assets/pdfs/

website:
  title: "Physics Voyage"
  site-url: "https://physicsvoyage-github-io.pages.dev/"
  favicon: assets/favicon.png
  search: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Articles          
      - href: courses.qmd
        text: Learn 
      - href: project.qmd
        text: Projects
      - href: resources.qmd
        text: Resources
      - text: About
        menu:
          - text: Your Story
            href: about.qmd#your-story
          - text: Mission
            href: about.qmd#mission
          - text: Team Members
            href: about.qmd#team-members
          - text: Contributors
            href: about.qmd#contributors
          - text: Contact
            href: about.qmd#contact
  reader-mode: true
  sidebar:
    - contents: posts.qmd # Creates a blog listing sidebar
      title: Recent Posts
  page-footer:
    center: "© 2026 Physics Voyage"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: sketchy
      dark: [sketchy, assets/styles/sketchy-dark.scss]
    highlight-style:
      light: github
      dark: dracula
    css: assets/styles/styles.css
    toc: true
    include-after-body:
      - assets/includes/newsletter-popup.html
      - assets/includes/back-to-top.html
